version: 1

info:
  id: platformsh/nextcloud
  name: Nextcloud
  description: |
      <p>This template builds Nextcloud on Platform.sh.  Nextcloud itself is downloaded on the fly during the build step, and pre-configured for use with MariaDB and Redis.  Add-on applications can be provided in a separate directory and will be merged into Nextcloud automatically during build.  (Self-update through the web interface is not supported.)</p>
      <p>The admin user is created automatically during the first deploy, and its name and password will be available in the deploy log.  Be sure to check for it there so you can log in.</p>
      <p>Nextcloud is a PHP-based groupware server with installable apps, file synchronization, and federated storage.</p>
  tags:
  - PHP
  - Groupware
  image: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='225' height='102.43'%3E%3Cg %3E%3Cpath d='M191.69 37.46a13.76 13.76 0 1 1-13.75 13.75 13.61 13.61 0 0 1 13.75-13.75m-158.39 0a13.76 13.76 0 1 1-13.75 13.75A13.61 13.61 0 0 1 33.3 37.46m79.37-17.91A31.67 31.67 0 1 1 81 51.21a31.52 31.52 0 0 1 31.66-31.66m0-19.55a51.37 51.37 0 0 0-49.2 37.23 33.31 33.31 0 1 0 0 28 51.15 51.15 0 0 0 98.31.48 33.3 33.3 0 1 0 0-28.92A51.4 51.4 0 0 0 112.67 0' style='fill-rule:evenodd' /%3E%3C/g%3E%3C/svg%3E
  notes:
    - heading: "Features"
      content: |
          PHP 7.4<br />
          MariaDB 10.4<br />
          Redis 5.0<br />
          Automatic TLS certificates<br />
          Nextcloud downloaded on the fly during build<br />

initialize:
  repository: git://github.com/platformsh-templates/nextcloud.git@master
  config: null
  files: []
  profile: Nextcloud
