# Platform.sh Project Initialization Template
#
# This file defines settings and workflow modifications that allow a git
# repository to be deployed to Platform.sh and its white-label partners. A
# project template can be a fully functioning ready-made application or a
# quick-start point for custom development work.
#
# It contains elements that affect the behaviour upon the initialisation of
# a new project (for example minimal plan sizes) as well as elements that
# allow Platform.sh to present it in a user interface (such as the description
# of the project, tags, an icon etc.).
#
# Once provisioned this file has no effects on the running project.  You
# are free to remove it.

# The schema is versioned so that we can establish code paths differently in the future if we need to change this.
version: 1

# Templates are a small amount of information supporting a template URL. Each template is selectable at the project-creation step.
info:
  # Unique machine name, prefaced by a vendor or organization identifier
  id: platformsh/elastic-apm
  # The human-readable name of the template.
  name: Elastic APM with Kibana
  # Human-readable descriptive text for the template. Supports limited HTML.
  description: |
    <p>This template builds Elastic APM (Application Performance Monitoring) with a Kibana front-end.
      It is intended as a complete self-contained monitoring solution, although authentication needs to be
        configured for your specific application.</p>

  # A list of tags associated with the template.
  tags:
  - Elasticsearch
  # An image URI (either base64-encoded or a URL) representing the template.
  image: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='206.25' height='225'%3E%3Cg %3E%3Cg %3E%3Cg %3E%3Cpath d='M155 78.75H96.19c0 1.41.84 2.81 1.12 3.94a103.27 103.27 0 0 1 3.69 21.09v17.44a103.27 103.27 0 0 1-3.66 21.09c0 1.41-.84 2.81-1.12 3.94H155a33.75 33.75 0 1 0 0-67.5z' style='fill:%2314a7df'/%3E%3Cpath d='M101 121.22v-17.44a103.27 103.27 0 0 0-3.66-21.09c0-1.41-.84-2.81-1.12-3.94H5.06a115 115 0 0 0 0 67.5h90.85c0-1.41.84-2.81 1.12-3.94a103.49 103.49 0 0 0 3.97-21.09z' style='fill:%23353535'/%3E%3Cpath d='M165.09 157.5H92a114.25 114.25 0 0 1-7.6 14.34 108.67 108.67 0 0 1-14.9 18.75l-5.91 5.63a111.25 111.25 0 0 1-12.94 10A111.28 111.28 0 0 0 112.5 225a112.5 112.5 0 0 0 93.75-50.06 57.36 57.36 0 0 0-41.16-17.44z' style='fill:%231dbab0'/%3E%3Cpath d='M84.37 171.84A114.25 114.25 0 0 0 92 157.5H9.37a111.25 111.25 0 0 0 41.25 48.75 140.15 140.15 0 0 0 12.94-9.38c2-1.68 3.94-3.65 5.91-5.62a128.06 128.06 0 0 0 14.9-19.41z' style='fill:%23009a8e'/%3E%3Cpath d='M69.19 34c-2-2-3.57-3.65-5.91-5.9a111.28 111.28 0 0 0-12.94-9.38 116.4 116.4 0 0 0-41 48.75h82.35a114.45 114.45 0 0 0-7.32-14.34A99.44 99.44 0 0 0 69.19 34z' style='fill:%23f6b019'/%3E%3Cpath d='M112.5 0a111.28 111.28 0 0 0-61.88 18.75 140.15 140.15 0 0 1 12.94 9.38c2 1.68 3.94 3.65 5.91 5.62a108.81 108.81 0 0 1 14.9 19.41A114.25 114.25 0 0 1 92 67.5h73.12a57.36 57.36 0 0 0 41.16-17.44A112.5 112.5 0 0 0 112.5 0z' style='fill:%23fcd00c'/%3E%3C/g%3E%3C/g%3E%3C/g%3E%3C/svg%3E
  # Additional notes displayed in the template's detail view.
  # Each note object is displayed as a small section heading with content below. Supports limited HTML.
  notes:
    - heading: "Apps & Services"
      content: "Elasticsearch 7.2"


# This key describes the initialization call made to the master environment at
# project creation time. This is part of the full v2 UI operation mode, which
# places project schema/options selection early in the creation process, rather
# than later as it exitss now. To allow this schema to be backwards-compatible,
# this key also gets mapped to the appropriate location in project.settings so
# that the current UI can have its own workflow overridden as well.
initialize:
  repository: git://github.com/platformsh-templates/elastic-apm.git@master
  config: null
  files: []
  profile: Elastic APM with Kibana
